[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:code-server]
command=code-server --config /home/euler/.config/code-server/config.yaml /home/euler
user=euler
directory=/home/euler
autostart=true
autorestart=true
stdout_logfile=/var/log/code-server.log
stderr_logfile=/var/log/code-server.log

[program:glvis-js-webserver]
command=python3 /home/euler/glvis-js/server/server.py
user=euler
directory=/home/euler/glvis-js
autostart=true
autorestart=true
stdout_logfile=/var/log/glvis-js-webserver.log
stderr_logfile=/var/log/glvis-js-webserver.log

[program:glvis-browser-server]
command=python3 /home/euler/glvis-js/server/browser-server.py
user=euler
directory=/home/euler/glvis-js
autostart=true
autorestart=true
stdout_logfile=/var/log/glvis-browser-server.log
stderr_logfile=/var/log/glvis-browser-server.log
