[supervisord]
nodaemon = true
user = euler
logfile = /tmp/supervisord.log

[program:glvis-js-webserver]
environment=HOME="/home/euler",USER="euler"
directory=/home/euler/glvis-js
redirect_stderr=true
stdout_logfile=/var/log/glvis-js-webserver.log
command=python3 -m http.server 8000 --bind 0.0.0.0

[program:glvis-browser-server]
environment=HOME="/home/euler",USER="euler"
redirect_stderr=true
stdout_logfile=/var/log/glvis-browser-server.log
command=/home/euler/glvis-js/glvis-browser-server

[program:code-server]
environment=HOME="/home/euler",USER="euler"
redirect_stderr=true
stdout_logfile=/var/log/code-server.log
command=code-server --config /home/euler/.config/code-server/config.yaml /home/euler